name: Publish to NPM
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node env
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build, test, and publish
        run: |
          npm ci
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
